### PR TITLE
#35 #37 #41

### PR DESCRIPTION
**Pull request by eLindros**
Fixes all open status issues

### CODE REVIEW

**Comment by fabfischer** [comment]
Hi @eLindros ,

thanks for the fixes. Would it be possible to squash all 6 commits into just one to have a cleaner git history?
Thanks a lot!

Fabian

**Comment by eLindros** [comment]
I'm a pretty noob with git and GitHub. How would I do that? I tried to erase those extraneous commits but only managed to reverse them. Do I have to erase the whole fork and start over?

**Comment by eLindros** [comment]
I mean: I'm pretty much a noob, not necessarily a pretty noob ;-)

**Comment by fabfischer** [comment]
Hi,

no problem. The easiest way would be to squash the 6 commits with a git gui client, like Fork or GitHub Desktop. I captured a possible approach with GitHub Desktop in a gif:

Sep-05-2022 19-52-23

You should select "squash x Commit" for the latest commit.

After squashing commits it is necessary to perform a "force push", because we changed the git history. And "squashing" also only makes sense before a feature branch is merged. It should be avoided to change git history in the "main" or "develop" branches.

Alternatively, I can squash the commits for you and push them into your fork and then merge the PR here. But I would appear as the author on the commit (and you as the co-author). If that's okay with you?

And in this case, you would have to check out your branch again if you want to look at it locally, because we changed the git history (or, to more precise: you have to delete your branch locally and get it from remote again). 

Just let me know which way you prefer.

Fabian

**Comment by eLindros** [comment]
Looks like it worked, thanks!

**Comment by fabfischer** [comment]
Great!

I will merge it and will add you as contributor in the next minor release. Thank you for the support.

**Pull request merged**
