### PR TITLE
Calculate market value sum in lineup

### PR DESCRIPTION
**Pull request by eLindros**
Maybe you find this feature also helpful. 

It
- calculates the sum of market values of selected players and
- updates the budget and team value accordingly.

For me this is useful when deciding which player should I sell before the next game day:

feature

### CODE REVIEW

**Comment by Quotic** [comment]
Perfect for matchday planning

**Comment by fabfischer** [comment]
Hi @eLindros ,

Thanks for the great feature. It's really a great help before a game day.

I'm just wondering if the whole feature wouldn't be better on the  page "Sell". Or maybe it should be listed with its own menu item. Then you could also make the calculation more explicit and transparent. You could there also use current offers from Kickbase (incl. sales bonuses for 3, 5 or 10 mio profit).

What do you think?

I'm the rest of the week on the road. But I could support you from next week with this feature, if you like?

Fabian

**Comment by eLindros** [comment]
Hi @fabfischer,

I also thought about putting this feature on the "Sell" page. But then I decided otherwise. The reason is, that I need to have a look on my lineup when deciding which player to sell. It happened to me, that I sold a defender and had only two left, and -- there is no formation for that :-)

But then again. It would be nice to incorporate the actual offers and also sales bonuses. I was looking for a quick solution and went with the market value. Also -- I'm really a novice in web programming and my time is quite limited. But I'm definitely open to enhance this feature.

I'm on vacation next week. So we could start on that after October 3.

eLindros

**Comment by Quotic** [comment]
I would prefer as a user if there was an extra MatchDay planner page for this. Maybe you can also calculate statistics for the players, like point average last 3 games etc. but to keep the load of the API (number of calls) low, it only makes sense to query this separately from the lineup.

**Comment by fabfischer** [comment]
Hi @eLindros ,

I will look into this feature asap. Perhaps you could rebase your PR onto the latest commit of the develop branch first? Thanks a lot! 
@Quotic's idea about a "MatchDay planner page" with more stats sounds interesting. With the latest version statistics of a player are also fetched. However, currently this data is only kept in the component and not in the global store. But we could change this easily

**Comment by eLindros** [comment]
Hi @fabfischer,

I needed to start over with my forked branch. Everything was quite messed up. I'm still pretty new to git and Github. Sorry. I will copy this feature in a new branch and start a new pull request.

**Pull request closed without merging**
